Improved packaging script.

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -1,5 +1,4 @@
 #!/bin/sh
-# $Id$
 # ###########################################################################
 #             Thomas Dreibholz's R Simulation Scripts Collection
 #                  Copyright (C) 2005-2022 Thomas Dreibholz
@@ -22,14 +21,36 @@
 #
 # Contact: dreibh@iem.uni-due.de
 
-#PACKAGE="rspsim-`date -u +%Y%m%d-%H%M%S`"
-#PACKAGE="rspsim-svn`svnversion`"
-PACKAGE="rspsim"
 
-cd /tmp && \
-rm -rf rspsim && \
-svn co https://svn1.tdr.iem.uni-due.de/svn/omnetpp/trunk/rspsim5 rspsim && \
-rm rspsim/make-package && \
-( find rspsim -name .svn | xargs rm -rf ) && \
-tar czvf $PACKAGE.tar.gz rspsim/ && \
-echo "DONE. Package is /tmp/$PACKAGE.tar.gz"
+skipSigning=0
+if [ $# -gt 0 ] ; then
+   if [ "$1" = "-skip-signing" ] ; then
+      skipSigning=1
+   else
+      echo >&2 "Usage: $0 [-skip-signing]"
+      exit 1
+   fi
+fi
+
+if [ ! -e version ] ; then
+   echo >&2 "ERROR: Missing file \"version\"!"
+   exit 1
+fi
+
+PACKAGE="`cat version | awk '{ print $1 }'`"
+VERSION="`cat version | awk '{ print $2 }'`"
+CURRENT_BRANCH=`git branch --show-current`
+
+
+echo "Archiving branch $CURRENT_BRANCH into $PACKAGE-$VERSION.tar.xz ..."
+rm -f $PACKAGE-$VERSION.tar.xz $PACKAGE-$VERSION.tar.xz.asc
+
+git config tar.tar.xz.command "xz -c"   # Enable .tar.xz output!
+git archive --format=tar.xz -o $PACKAGE-$VERSION.tar.xz --prefix=$PACKAGE-$VERSION/ $CURRENT_BRANCH
+
+if [ $skipSigning -eq 0 ] ; then
+   echo "Signing archive ..."
+   gpg -sab  $PACKAGE-$VERSION.tar.xz
+fi
+   
+du -sk  $PACKAGE-$VERSION.tar.xz*
