Updated SimProcTC to latest version.

diff --git a/toolchain/archive-simulation b/toolchain/archive-simulation
--- a/toolchain/archive-simulation
+++ b/toolchain/archive-simulation
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -eu
 # ###########################################################################
 #             Thomas Dreibholz's R Simulation Scripts Collection
 #                  Copyright (C) 2005-2025 Thomas Dreibholz
@@ -21,30 +21,32 @@
 #
 # Contact: thomas.dreibholz@gmail.com
 
-while [ $# -gt 0 ] ; do
-   if [ ! -e $1.R ] ; then
-      echo "ERROR: $1.R does not exist!"
-      exit
-   fi
-   if [ ! -e plot-$1.R ] ; then
-      echo "ERROR: plot-$1.R does not exist!"
-      exit
-   fi
-   if [ ! -e $1 ] ; then
-      echo "ERROR: $1 directory does not exist!"
-      exit
-   fi
+# ====== Check parameters ===================================================
+if [ $# -lt 1 ] ; then
+   echo >&2 "Usage: $0 [Simulation]"
+   exit 1
+fi
+if [ ! -e "$1".R ] ; then
+   echo "ERROR: $1.R does not exist!"
+   exit
+fi
+if [ ! -e plot-"$1".R ] ; then
+   echo "ERROR: plot-$1.R does not exist!"
+   exit
+fi
+if [ ! -e "$1" ] ; then
+   echo "ERROR: $1 directory does not exist!"
+   exit
+fi
 
 
-   DESTINATION=$2
-   if [ x$DESTINATION = "x" ] ; then
-      DESTINATION=.
-   fi
+if [ $# -gt 1 ] ; then
+   DESTINATION="$2"
+else
+   DESTINATION="."
+fi
 
 
-   echo "Archiving to $DESTINATION/$1.tar.xz ..." && \
-   tar cf - $1.R plot-$1.R $1/Results | xz -T0 -c >$DESTINATION/$1.tar.xz
-
-
-   shift
-done
+echo "Archiving to $DESTINATION/$1.tar.bz2 ..." && \
+R --vanilla <plot-"$1".R && \
+tar cjf "$DESTINATION"/"$1".tar.bz2 "$1".R plot-"$1".R "$1".pdf "$1"/Results
